# Título do agente
AI_AGENT_TITLE = "Meu agente no Langflow"

# Descrição do agente
AI_AGENT_DESCRIPTION = "Este é um exemplo de descrição de agente desenvolvido no LangFlow"

# Mensagem de boas-vindas
WELCOME_MESSAGE = "Olá! Como posso te ajudar hoje?"

# URL da API do LangFlow
LANGFLOW_API_URL = "<URL_API"

# Token da API do LangFlow
LANGFLOW_API_TOKEN = "<API_TOKEN"

# Dados do agente em formato JSON
LANGFLOW_API_DATA = '{"input_value": "message", "output_type": "chat", "input_type": "chat", "tweaks": {"ChatInput-j2SA7": {}, "ChatOutput-KsDth": {}, "ParseData-6oE3v": {}, "OpenAIModel-3NTPQ": {}, "File-4zYYE": {}, "Prompt-EGiaz": {}}}'
