# Título do agente
AI_AGENT_TITLE = "Meu agente de IA no Langflow"

# Descrição do agente
AI_AGENT_DESCRIPTION = "Este é um exemplo de descrição de agente desenvolvido no LangFlow. Siga as instruções abaixo para integrar sua API do Langflow ao Streamlit."

# Mensagem de boas-vindas
WELCOME_MESSAGE = "Olá! Como posso te ajudar hoje?"

# URL da API do LangFlow
LANGFLOW_API_URL = "<URL_API>"

# Token da API do LangFlow
LANGFLOW_API_TOKEN = "<API_TOKEN>"

# Dados do agente em formato JSON
LANGFLOW_API_DATA = '{"input_value": "", "output_type": "chat", "input_type": "chat"}'
