# Corpo da solicitação à API do Langflow (alteração é opcional)
DATA_JSON={"input_value": "", "output_type": "chat", "input_type": "chat"}

# URL da sua API
API_URL=<URL_DA_API>

# TOKEN DE ACESSO À API DO LANGFLOW
API_TOKEN=<TOKEN_DA_API>

# TÍTULO CRIATIVO DO SEU AGENTE DE ia
AGENT_TITLE=🔎Meu agente de IA

# DESCRIÇÃO DO SEU AGENTE DE IA
AGENT_DESCRIPTION= Exemplo de descrição de agente de IA.

# PERGUNTA INICIAL DA IA
ASSISTANT_INITIAL_MESSAGE=Olá, como posso te ajudar hoje?
